import { useMemo, useState } from "react"
import { IconAdjustments, IconArrowRight, IconBolt, IconCheck, IconCommand, IconLeaf, IconMapPin, IconMinus, IconPlus, IconSearch, IconShieldCheck, IconShoppingBag, IconTrees } from "@tabler/icons-react"
import { CommandMenu, openCommandMenu, type CommandMenuAction } from "@/components/ui/command-menu"
import { HalftoneDots } from "@/components/ui/halftone-dots"
import { NavigationMenu, NavigationMenuItem, NavigationMenuList, navigationMenuTriggerStyle } from "@/components/ui/navigation-menu"
import { Toasts, toast } from "@/components/ui/toast"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Separator } from "@/components/ui/separator"
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group"
import "./App.css"

type Project={id:string;name:string;place:string;type:string;price:number;standard:string;vintage:string;summary:string;color:string;icon:"forest"|"energy";featured?:boolean}
const projects:Project[]=[
{id:"forest",name:"Alto Mayo Forest",place:"San Martín, Peru",type:"Forest conservation",price:18.5,standard:"VCS",vintage:"2022",summary:"Avoided deforestation and community-led forest protection.",color:"#315c42",icon:"forest",featured:true},
{id:"cook",name:"Clean Cooking Kenya",place:"Kisumu, Kenya",type:"Household energy",price:12.75,standard:"Gold Standard",vintage:"2023",summary:"Efficient cookstoves designed to reduce fuel use and indoor smoke.",color:"#a86236",icon:"energy"},
{id:"mangrove",name:"Sundarbans Mangroves",place:"West Bengal, India",type:"Blue carbon",price:24,standard:"VCS + CCB",vintage:"2022",summary:"Mangrove restoration with local stewardship and coastal resilience.",color:"#28646b",icon:"forest"},
{id:"solar",name:"Rajasthan Solar",place:"Rajasthan, India",type:"Renewable energy",price:8.5,standard:"Gold Standard",vintage:"2021",summary:"Grid-connected solar generation displacing fossil electricity.",color:"#b38635",icon:"energy"},
{id:"peat",name:"Katingan Peatlands",place:"Central Kalimantan, Indonesia",type:"Peatland protection",price:16.25,standard:"VCS + CCB",vintage:"2022",summary:"Protection of carbon-rich peatland and surrounding habitats.",color:"#4b5541",icon:"forest"},
{id:"bio",name:"Oregon Biochar",place:"Oregon, USA",type:"Carbon removal",price:118,standard:"Puro.earth",vintage:"2024",summary:"Biomass converted into stable biochar for durable carbon storage.",color:"#4f4b47",icon:"energy"},
]
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",minimumFractionDigits:n%1?2:0}).format(n)
function ProjectArt({p}:{p:Project}){return <div className="project-art" style={{background:p.color}}><div className="sun"/><div className="ridge r1"/><div className="ridge r2"/>{p.icon==="forest"?<IconTrees/>:<IconBolt/>}<span>{p.place.split(",")[1]?.trim()||p.place}</span></div>}
function App(){
 const [filter,setFilter]=useState<readonly string[]>(["All"]); const [query,setQuery]=useState(""); const [selected,setSelected]=useState<Project|null>(null); const [cart,setCart]=useState<Record<string,number>>({}); const [cartOpen,setCartOpen]=useState(false); const [checkout,setCheckout]=useState(false)
 const visible=useMemo(()=>projects.filter(p=>(filter.includes("All")||filter.some(f=>p.type.includes(f)))&&(p.name+p.place+p.type).toLowerCase().includes(query.toLowerCase())),[filter,query])
 const count=Object.values(cart).reduce((a,b)=>a+b,0); const total=projects.reduce((a,p)=>a+(cart[p.id]||0)*p.price,0)
 const add=(p:Project,n=1)=>{setCart(c=>({...c,[p.id]:(c[p.id]||0)+n}));toast({message:`${n} tonne${n>1?"s":""} of ${p.name} added`,state:"success"})}
 const setQty=(id:string,n:number)=>setCart(c=>({...c,[id]:Math.max(0,n)}))
 const commands:CommandMenuAction[]=[{id:"search",label:"Search projects",keywords:["find","browse"],icon:<IconSearch size={16}/>,action:()=>document.getElementById("search")?.focus()},{id:"cart",label:`Open portfolio cart (${count})`,keywords:["basket","checkout"],icon:<IconShoppingBag size={16}/>,action:()=>setCartOpen(true)},{id:"forest",label:"Show forest projects",keywords:["filter","nature"],icon:<IconTrees size={16}/>,action:()=>setFilter(["Forest"])},{id:"all",label:"Show all projects",keywords:["reset"],icon:<IconLeaf size={16}/>,action:()=>setFilter(["All"])}]
 return <div className="min-h-svh bg-[#f4f4ef] text-[#172019]">
  <header className="sticky top-0 z-40 border-b border-black/10 bg-[#f4f4ef]/90 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center px-5"><button className="brand" onClick={()=>scrollTo(0,0)}><span><IconLeaf size={18}/></span>COMMON GROUND</button><NavigationMenu className="hidden md:block ml-8"><NavigationMenuList><NavigationMenuItem><button className={navigationMenuTriggerStyle()} data-active>Marketplace</button></NavigationMenuItem><NavigationMenuItem><button className={navigationMenuTriggerStyle()} onClick={()=>document.getElementById("how")?.scrollIntoView()}>How it works</button></NavigationMenuItem><NavigationMenuItem><button className={navigationMenuTriggerStyle()} onClick={()=>openCommandMenu()}><IconCommand size={15}/> Command</button></NavigationMenuItem></NavigationMenuList></NavigationMenu><div className="ml-auto flex items-center gap-2"><Badge variant="outline" className="hidden sm:flex">Concept store</Badge><Button variant="outline" onClick={()=>setCartOpen(true)}><IconShoppingBag/> Cart <span className="cart-count">{count}</span></Button></div></div></header>
  <main>
   <section className="hero"><HalftoneDots src={`${import.meta.env.BASE_URL}carbon-landscape.svg`} accent="#49704f" gradient={["#dde5d4","#a7b9a0"]} className="hero-dots"/><div className="hero-copy"><Badge className="mb-5 bg-[#173d28] text-white">Curated climate projects</Badge><h1>Put your climate budget<br/>to work.</h1><p>Browse independent carbon projects with clear pricing and project-level details. Build a portfolio by the tonne.</p><div className="flex flex-wrap gap-3"><Button size="lg" onClick={()=>document.getElementById("projects")?.scrollIntoView()}>Browse projects <IconArrowRight/></Button><Button size="lg" variant="outline" onClick={()=>document.getElementById("how")?.scrollIntoView()}>How we evaluate</Button></div></div><div className="hero-stat"><span>From</span><strong>$8.50</strong><small>per demo tonne</small></div></section>
   <section id="projects" className="market"><div className="section-head"><div><span className="eyebrow">THE MARKETPLACE</span><h2>Choose the work you back.</h2></div><p>Project descriptions, standards, prices and vintages shown here are illustrative demo data, not an offer of real credits.</p></div>
    <div className="toolbar"><div className="search"><IconSearch/><Input id="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search project or region"/></div><ToggleGroup value={filter} onValueChange={v=>setFilter(v.length?v:["All"])} variant="outline"><ToggleGroupItem value="All">All</ToggleGroupItem><ToggleGroupItem value="Forest">Forest</ToggleGroupItem><ToggleGroupItem value="Renewable">Energy</ToggleGroupItem><ToggleGroupItem value="removal">Removal</ToggleGroupItem></ToggleGroup><Button variant="outline" className="md:hidden"><IconAdjustments/> Filter</Button></div>
    <div className="project-grid">{visible.map(p=><Card key={p.id} className="project-card py-0 overflow-hidden"><button className="text-left" onClick={()=>setSelected(p)}><ProjectArt p={p}/><CardContent className="p-5"><div className="flex items-start justify-between gap-3"><div><Badge variant="secondary" className="mb-3">{p.type}</Badge><h3>{p.name}</h3><p className="location"><IconMapPin/> {p.place}</p></div>{p.featured&&<Badge className="bg-[#d5e6c9] text-[#173d28]">Featured</Badge>}</div><p className="summary">{p.summary}</p><Separator/><div className="project-meta"><div><span>Standard</span><strong>{p.standard}</strong></div><div><span>Vintage</span><strong>{p.vintage}</strong></div><div className="price"><span>per tonne</span><strong>{money(p.price)}</strong></div></div></CardContent></button><div className="px-5 pb-5"><Button className="w-full" onClick={()=>add(p)}>Add 1 tonne <IconPlus/></Button></div></Card>)}</div>
   </section>
   <section id="how" className="how"><div><span className="eyebrow">A BETTER RECEIPT</span><h2>Know what sits behind every tonne.</h2><p>This concept puts verification, vintage, location and project method beside the price, before checkout.</p></div><div className="steps">{[["01","Compare","Filter by project type, geography, standard and price."],["02","Build","Mix projects and quantities into one portfolio."],["03","Review","See every line item before a demo confirmation."]].map(s=><div key={s[0]}><span>{s[0]}</span><strong>{s[1]}</strong><p>{s[2]}</p></div>)}</div></section>
  </main>
  <footer><div className="brand"><span><IconLeaf size={18}/></span>COMMON GROUND</div><p>Marketplace concept. No inventory, purchase, retirement, or environmental claim is created by this demo.</p></footer>
  <Dialog open={!!selected} onOpenChange={o=>!o&&setSelected(null)}>{selected&&<DialogContent className="max-w-2xl p-0 overflow-hidden"><ProjectArt p={selected}/><div className="p-6"><DialogHeader><DialogTitle className="text-2xl">{selected.name}</DialogTitle><DialogDescription>{selected.place}</DialogDescription></DialogHeader><p className="my-5 text-sm leading-6">{selected.summary} This is a product concept using illustrative project information. A live marketplace would link registry records, monitoring reports and issuance status here.</p><div className="detail-grid"><div><span>Method</span><strong>{selected.type}</strong></div><div><span>Verification</span><strong>{selected.standard}</strong></div><div><span>Vintage</span><strong>{selected.vintage}</strong></div><div><span>Demo price</span><strong>{money(selected.price)} / t</strong></div></div><Button className="mt-6 w-full" onClick={()=>{add(selected);setSelected(null)}}>Add one tonne</Button></div></DialogContent>}</Dialog>
  <Dialog open={cartOpen} onOpenChange={setCartOpen}><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>Your portfolio</DialogTitle><DialogDescription>Demo cart. Nothing here can be purchased or retired.</DialogDescription></DialogHeader>{count===0?<div className="empty"><IconShoppingBag/><strong>Your cart is clear</strong><p>Add tonnes from one or more projects.</p></div>:<div>{projects.filter(p=>cart[p.id]).map(p=><div className="cart-row" key={p.id}><div><strong>{p.name}</strong><span>{money(p.price)} / tonne</span></div><div className="qty"><Button size="icon-sm" variant="outline" onClick={()=>setQty(p.id,cart[p.id]-1)}><IconMinus/></Button><b>{cart[p.id]}</b><Button size="icon-sm" variant="outline" onClick={()=>setQty(p.id,cart[p.id]+1)}><IconPlus/></Button></div><strong>{money(p.price*cart[p.id])}</strong></div>)}<Separator/><div className="total"><span>Portfolio total</span><strong>{money(total)}</strong></div><Button size="lg" className="w-full" onClick={()=>{setCartOpen(false);setCheckout(true)}}>Review demo checkout <IconArrowRight/></Button></div>}</DialogContent></Dialog>
  <Dialog open={checkout} onOpenChange={setCheckout}><DialogContent><DialogHeader><DialogTitle>Review, not payment</DialogTitle><DialogDescription>This final screen demonstrates the checkout experience.</DialogDescription></DialogHeader><div className="review"><div><IconShieldCheck/><span><strong>{count} demo tonnes</strong><small>Across {Object.values(cart).filter(Boolean).length} projects</small></span></div><div><span>Illustrative total</span><strong>{money(total)}</strong></div></div><div className="notice"><IconCheck/> No card, payment, credit issuance, retirement, ownership transfer or certificate is created.</div><Button size="lg" onClick={()=>toast({message:"Demo complete. Nothing was charged or retired.",state:"success"})}>Complete demo</Button></DialogContent></Dialog>
  <CommandMenu actions={commands}/><Toasts position="bottom-right"/>
 </div>
}
export default App
